Src= src/flip.c\
src/Primenumber.c\
src/factorial.c\
src/isPalindrome.c\
src/strcat.c\
src/strcmp.c\
src/strcpy.c\
src/strlen.c\
src/reset.c\
src/set.c\
src/vsum.c

INC= -Iinc


#build: src/flip.c src/isPrime.c src/factorial.c src/isPalindrome.c src/mystrcat.c src/mystrcmp.c src/mystrcpy.c src/mystrlen.c src/reset.c src/set.c src/vsum.c
#	gcc $(INC) $(Src) -c

build: $(Src)
	gcc $(INC) $(Src) -c